// Mocks generated by Mockito 5.4.6 from annotations
// in battle_for_the_cats/test/services/game_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:battle_for_the_cats/models/game_room.dart' as _i5;
import 'package:battle_for_the_cats/models/match_result.dart' as _i7;
import 'package:battle_for_the_cats/services/game_flow_service.dart' as _i8;
import 'package:battle_for_the_cats/services/matchmaking_service.dart' as _i6;
import 'package:battle_for_the_cats/services/room_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RoomService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomService extends _i1.Mock implements _i2.RoomService {
  MockRoomService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateRoomCode() =>
      (super.noSuchMethod(
            Invocation.method(#generateRoomCode, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateRoomCode, []),
            ),
          )
          as String);

  @override
  _i4.Future<String> createRoom(String? hostId) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [hostId]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#createRoom, [hostId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> joinRoom(String? roomCode, String? guestId) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [roomCode, guestId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i5.GameRoom?> watchRoom(String? roomCode) =>
      (super.noSuchMethod(
            Invocation.method(#watchRoom, [roomCode]),
            returnValue: _i4.Stream<_i5.GameRoom?>.empty(),
          )
          as _i4.Stream<_i5.GameRoom?>);

  @override
  _i4.Future<void> leaveRoom(String? roomCode, String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [roomCode, playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoom(String? roomCode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoom, [roomCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isHost(_i5.GameRoom? room, String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#isHost, [room, playerId]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [MatchmakingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchmakingService extends _i1.Mock
    implements _i6.MatchmakingService {
  MockMatchmakingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> joinMatchmaking(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#joinMatchmaking, [playerId]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#joinMatchmaking, [playerId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Stream<_i7.MatchResult?> watchMatchmaking(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMatchmaking, [playerId]),
            returnValue: _i4.Stream<_i7.MatchResult?>.empty(),
          )
          as _i4.Stream<_i7.MatchResult?>);

  @override
  _i4.Future<void> cancelMatchmaking(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelMatchmaking, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isHostInMatch(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#isHostInMatch, [playerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [GameFlowService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameFlowService extends _i1.Mock implements _i8.GameFlowService {
  MockGameFlowService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> rollDice(String? roomCode, String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#rollDice, [roomCode, playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmRoll(String? roomCode, String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmRoll, [roomCode, playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> placeBets(
    String? roomCode,
    String? playerId,
    Map<String, int>? bets,
    Map<String, String?>? itemPlacements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeBets, [
              roomCode,
              playerId,
              bets,
              itemPlacements,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> nextTurn(String? roomCode, String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#nextTurn, [roomCode, playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
